from __future__ import annotations

import logging
from typing import Callable

from pydantic import BaseModel

from docai.discovery.datatypes import FileManifest, ManifestEntry
from docai.extractor.datatypes import Entity, EntityCategory, FileAnalysis, FileType
from docai.extractor.errors import ExtractionError
from docai.llm.errors import LLMError
from docai.llm.service import LLMService

# --- Structured output models ---


class FileTypeAndDeps(BaseModel):
    file_type: FileType
    dependencies: list[str]


class EntityList(BaseModel):
    entities: list[Entity]


logger = logging.getLogger(__name__)


# --- Chunking helpers ---


def _build_chunks(
    lines: list[str],
    chunk_size: int,
    header_size: int,
    overlap: int,
) -> list[str]:
    if len(lines) <= chunk_size:
        return ["\n".join(lines)]
    header = lines[:header_size]
    remaining = lines[header_size:]
    step = chunk_size - overlap
    header_str = "\n".join(header)
    chunks = []
    for i in range(0, len(remaining), step):
        body = "\n".join(remaining[i : i + chunk_size])
        chunks.append(f"{header_str}\n# ...\n{body}")
    return chunks


def _merge_entities(*entity_lists: EntityList) -> EntityList:
    seen: set[tuple[str, EntityCategory]] = set()
    merged: list[Entity] = []
    for entity_list in entity_lists:
        for entity in entity_list.entities:
            key = (entity.name, entity.category)
            if key not in seen:
                seen.add(key)
                merged.append(entity)
    return EntityList(entities=merged)


# --- System prompts ---

_SYSTEM_PROMPT_TYPE_AND_DEPS = """\
You are an expert code analyst. Your task is to classify a file and identify \
which other project files it directly depends on.

File type rules:
- source_file: a programming language file with functions, classes, or other \
  named entities (e.g. .py, .rs, .js, .go)
- source_like_config: not a programming language, but contains import-like \
  constructs that reference other project files (e.g. .scss with @use, \
  Makefile with include, HTML template with {% import %})
- config_file: a configuration file with no imports to other project files \
  (e.g. .yaml, .toml, .json config, .env)
- other: cannot be classified into any of the above categories

Dependency rules:
- A dependency is a file that appears in an explicit import, include, require, \
  use, or open statement visible in the file content.
- Only return files whose exact path appears in the provided project file list.
- Do not include standard library modules, built-in packages, or third-party \
  packages.
- Only include direct dependencies — files this file itself references, not \
  transitive ones.
- If file_type is source_like_config, dependencies must not be empty — \
  source_like_config means the file imports other project files.
- If there are no project-internal dependencies, return an empty list.
- Do not resolve language module system names to file paths. Module namespace \
  paths — Rust `use crate::foo`, Haskell module names (e.g. \
  `import Data.Set.Internal`), Java/Kotlin package imports, Python absolute \
  imports, and similar — are not file references and must never be mapped to \
  project files. Only imports that contain an explicit relative or absolute \
  file path string produce dependencies (e.g. `from ./utils import`, \
  `#include "dict.h"`, `@use '_variables'`, `from .exceptions import`).

Do not infer dependencies from file naming, directory co-location, or semantic \
similarity. A file is only a dependency if this file explicitly imports or \
includes it.\
"""

_SYSTEM_PROMPT_ENTITIES = """\
You are an expert code analyst. Your task is to extract the named entities \
from a source file.

Entity categories:
- callable: functions, methods, constructors, lambdas, closures, methods \
  generated by macro calls (e.g. attr_reader, attr_accessor, delegate in Ruby), \
  Haskell data constructors (e.g. `DecodeError` and `EncodeError` in \
  `data UnicodeException = DecodeError ... | EncodeError ...`), \
  and module-level variables assigned to a function or arrow function \
  (e.g. `const foo = () => ...`, `const bar = function() {...}`)
- macro: preprocessor macros, compile-time code generators, and macro call \
  sites that transform structure (e.g. the attr_reader call itself, not the \
  methods it generates)
- type: classes, interfaces, structs, enums, type aliases, protocols, traits
- value: module-level constants, global variables, exported values, \
  and Scala singleton/companion objects (`object Foo`)
- implementation: impl blocks, trait implementations, typeclass instances, \
  mixin applications (language constructs that attach behaviour to a type \
  without being the type), and Haskell `deriving` clauses — one implementation \
  entity per listed typeclass (e.g. `deriving (Eq, Show)` → two entities: \
  `Eq` and `Show`, both implementation)

Field rules:
- name: the entity's own unqualified name — never include the parent type or \
  module in the name field (e.g. use "Show", not "Show MyType"; use "run", \
  not "MyClass.run"; use "Builder", not "Ecto.Query.Builder")
- kind: the specific language construct (e.g. "function", "class", "method", \
  "constant", "enum")
- parent: dotted scope path from module root for nested entities \
  (e.g. "OuterClass.InnerClass"), or null if top-level
- signature: the declaration line or signature, or null if not applicable

Extraction rules:
- Extract all named entities visible at the module level and nested within \
  types. Do not extract anonymous or local-scope-only constructs.
- Do not recurse into function or method bodies — only recurse into type \
  bodies (classes, structs, enums, interfaces, and TypeScript `type` object \
  shape literals). Extract their named members including properties, methods, \
  and construct signatures (e.g. `new` in a TypeScript type).
- For typeclass or trait instances (Haskell, Scala, Rust), the entity name is \
  the bare typeclass/trait name (e.g. "Show", "Eq", "Serialize") — category \
  is implementation.
- Haskell `deriving` clauses count as typeclass instances — extract each \
  typeclass name listed as an implementation entity.
- Ruby `attr_reader`, `attr_accessor`, `attr_writer` call sites are macro \
  entities. The methods they generate are callable entities.
- Methods generated by macros (e.g. Ruby attr_reader :name generates #name) \
  are callable, not macro.\
"""


# --- Validators ---


def _make_type_and_deps_validator(
    file_manifest: FileManifest,
) -> Callable[[str | BaseModel], str | None]:
    all_files = set(file_manifest)

    def validate(result: str | BaseModel) -> str | None:
        if not isinstance(result, FileTypeAndDeps):
            return "Expected a FileTypeAndDeps object"
        invalid = [d for d in result.dependencies if d not in all_files]
        if invalid:
            return (
                f"The following paths are not in the project file list: "
                f"{', '.join(invalid)}. Only return paths that appear exactly "
                f"in the provided project_files list."
            )
        if result.file_type == FileType.source_like_config and not result.dependencies:
            return (
                "file_type is source_like_config but dependencies is empty. "
                "source_like_config means the file imports other project files. "
                "Either provide a non-empty dependencies list or correct the file_type."
            )
        return None

    return validate


# --- Internal extraction calls ---


async def _extract_type_and_deps(
    file_path: str,
    content: str,
    manifest_entry: ManifestEntry,
    file_manifest: FileManifest,
    llm_service: LLMService,
) -> FileTypeAndDeps:
    file_list = "\n".join(f"- {p}" for p in sorted(file_manifest))
    lang = manifest_entry.language or "unknown"
    prompt = (
        f"Classify the following file and identify its project-internal dependencies.\n\n"
        f"<file>\n"
        f"Path: {file_path}\n"
        f"Language: {lang}\n"
        f"Classification: {manifest_entry.classification.value}\n"
        f"</file>\n\n"
        f"<project_files>\n"
        f"Only return dependencies whose paths appear in this list:\n"
        f"{file_list}\n"
        f"</project_files>\n\n"
        f"<file_content>\n"
        f"```{lang}\n{content}\n```\n"
        f"</file_content>"
    )
    result = await llm_service.generate(
        prompt,
        system_prompt=_SYSTEM_PROMPT_TYPE_AND_DEPS,
        structured_output=FileTypeAndDeps,
        validator=_make_type_and_deps_validator(file_manifest),
    )
    return result  # type: ignore[return-value]


async def _extract_entities(
    file_path: str,
    content: str,
    manifest_entry: ManifestEntry,
    llm_service: LLMService,
) -> EntityList:
    lang = manifest_entry.language or "unknown"
    prompt = (
        f"Extract all named entities from the following source file.\n\n"
        f"<file>\n"
        f"Path: {file_path}\n"
        f"Language: {lang}\n"
        f"</file>\n\n"
        f"<file_content>\n"
        f"```{lang}\n{content}\n```\n"
        f"</file_content>"
    )
    result = await llm_service.generate(
        prompt,
        system_prompt=_SYSTEM_PROMPT_ENTITIES,
        structured_output=EntityList,
    )
    return _merge_entities(result)  # type: ignore[arg-type]


async def _extract_entities_chunked(
    file_path: str,
    content: str,
    manifest_entry: ManifestEntry,
    llm_service: LLMService,
    *,
    chunk_size: int = 750,
    header_size: int = 100,
    overlap: int = 200,
) -> EntityList:
    lines = content.splitlines()
    chunks = _build_chunks(
        lines, chunk_size=chunk_size, header_size=header_size, overlap=overlap
    )

    if len(chunks) > 1:
        logger.warning(
            "Large file '%s' (%d lines) split into %d chunks — "
            "entity parent attribution may be imperfect",
            file_path,
            len(lines),
            len(chunks),
        )

    results: list[EntityList] = []
    for i, chunk_content in enumerate(chunks):
        try:
            entity_list = await _extract_entities(
                file_path, chunk_content, manifest_entry, llm_service
            )
            results.append(entity_list)
        except LLMError:
            logger.warning(
                "Entity extraction failed for chunk %d/%d of '%s' — skipping",
                i + 1,
                len(chunks),
                file_path,
            )

    return _merge_entities(*results) if results else EntityList(entities=[])


# --- Public entry point ---


async def extract_with_llm(
    file_path: str,
    content: str,
    manifest_entry: ManifestEntry,
    file_manifest: FileManifest,
    llm_service: LLMService,
) -> FileAnalysis:
    try:
        type_and_deps = await _extract_type_and_deps(
            file_path, content, manifest_entry, file_manifest, llm_service
        )
        if type_and_deps.file_type == FileType.source_file:
            entity_list = await _extract_entities_chunked(
                file_path, content, manifest_entry, llm_service
            )
            entities = entity_list.entities
        else:
            entities = []
    except LLMError as exc:
        raise ExtractionError(
            code="EXTRACTION_LLM_FAILED",
            message=f"File Analysis failed for {file_path}",
        ) from exc

    return FileAnalysis(
        file_path=file_path,
        file_type=type_and_deps.file_type,
        entities=entities,
        dependencies=type_and_deps.dependencies,
    )
