providers:
  google:
    api_key_env: GEMINI_API_KEY
    # api_key: xxxxxx  # alternative to api_key_env

models:
  gemini-2.5-flash:
    name: gemini-2.5-flash
    # generation:
    #   temperature: 0.2
    #   max_output_tokens: 2048
    #   top_p: 0.95
  gemini-1.5-pro:
    name: gemini-1.5-pro
    generation:
      temperature: 0.4
      max_output_tokens: 4096

profiles:
  default:
    - provider: google
      model: gemini-2.5-flash
    - provider: google # fallback
      model: gemini-1.5-pro
  fast:
    - provider: google
      model: gemini-2.5-flash

globals:
  max_concurrent_requests: 5 # default is 10

retry:
  max_retries: 5 # default is 3
  retry_delay: 60000 # in ms. default is 1000
  retry_on: ["5xx", "408", "429"]
  max_validation_retries: 2 # default is 2

cache:
  cache_dir: .docai/cache/llm # default: .docai/cache/llm
  max_disk_size: 1_000_000_000 # default: 1GB
  max_age: 86400 # in sec. default: 1 day
  max_lru_size: 1000 # default: 1000
  model_config_strategy: newest # default: newest, also possible: best_match and exact_match
